### ISSUE TITLE
ESPHome bot does not update beta with newer stable version

### ISSUE THREAD

**Issue by TheZoker** [hassio-addons/repository-beta#20]
# Problem/Motivation

On the esphome/hassio repo, the esphomebot does automatically update the beta version with the latest stable version:
https://github.com/esphome/hassio/commit/9bd7e910ac66920f99e0a8c150b2b03e34b7e0c2#diff-9747da7a39ecebfec5e92cf2271a35f63433581f59080a4ac1859e1cc7999109

On this repo however, this does not happen. The bot only seems to update the beta version with new beta releases even if there is a newer stable version. That is also the reason, why frenck had to manually update the version here:
https://github.com/hassio-addons/repository-beta/commit/91d92043ee4014c63dc64f0d7cb46194fa992ece

## Expected behavior

Update also the beta version, if there is a newer stable version

## Actual behavior

Beta version is only updated on new beta release

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

I'm not sure, how or where the bot is setup, but I think that this setup needs to be adjusted to mimic the behavior similar to the esphome/hassio repo.

**Comment by frenck** [comment]
I manually bumped for a different reason, so not sure how you came to that conclusion even remotely.

![image](https://user-images.githubusercontent.com/195327/108330593-0ec62380-71ce-11eb-9549-1709943893bd.png)

Its up to them to release a beta, not me.

**Comment by TheZoker** [comment]
The latest esphome version is 1.16.1. 
On the esphome hassio repo, the bot did update the beta accordingly:
https://github.com/esphome/hassio/blob/master/esphome-beta/config.json#L45

This is not the case for this beta repo here:
https://github.com/hassio-addons/repository-beta/blob/master/esphome/config.json#L33

So the bot does update if there is a new beta version, which is fine. But when a new stable version is released, that is superior to the beta version, the bot should also update it just like in the esphome repo. 

I hope this clears it up

**Comment by frenck** [comment]
Again, not a decision or up to this repository.

**Comment by TheZoker** [comment]
Do you know, where the esphome bot is configured?
